name: automerge-master

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: [master, dressnpcs_master, gomove_master, multivendor_master, objscale_master, playeritemgossip_master]
        pch: [ON, OFF]
    env:
      BRANCH: ${{ matrix.branch }}
      PCH: ${{ matrix.pch }}

    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 0

    - name: Configure user
      run: |
        git config user.email "rochet2@post.com" && git config user.name "Rochet2"

    - name: Merge TC
      run: |
        git status
        git remote add Trinity https://github.com/TrinityCore/TrinityCore.git
        git fetch Trinity master
        git merge -m "Merge TrinityCore master to ${BRANCH} [skip ci]" Trinity/master
        git submodule update --init --recursive
        git status

    - name: Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev clang-11
    - name: Setup
      run: |
        mkdir bin
        cd bin
        cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=$PCH -DUSE_SCRIPTPCH=$PCH -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11
        cd ..
    - name: Build
      run: |
        cd bin
        make -j 4 -k && make install
    - name: Unit tests
      run: |
        cd bin
        make test
    - name: Check executables
      run: |
        cd bin/check_install/bin
        ./bnetserver --version
        ./worldserver --version

    - name: Push changes
      if: matrix.pch == 'ON'
      run: |
        git push
