name: GCC

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        branch: [
          3.3.5,
          transmog_3.3.5,
          transmogvendor_3.3.5,
          reforging_3.3.5,
          multivendor_3.3.5,
          multitrainer_3.3.5,
          playeritemgossip_3.3.5,
          dressnpcs_3.3.5,
          objscale_3.3.5,
          gomove_3.3.5
        ]
        pch: [ON, OFF]
        fetch_depth: [1000]
    env:
      BRANCH: ${{ matrix.branch }}
      PCH: ${{ matrix.pch }}
      DEPTH: ${{ matrix.fetch_depth }}

    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        repository: Rochet2/TrinityCore
        fetch-depth: ${{ matrix.fetch_depth }}
    - name: Merge TC
      run: |
        git status	
        git remote add Trinity https://github.com/TrinityCore/TrinityCore.git	
        git fetch --depth=$DEPTH Trinity 3.3.5	
        git merge -m "Merge TrinityCore 3.3.5 to ${BRANCH} [skip ci]" Trinity/3.3.5
        git submodule update --init --recursive
        git status

    - name: Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    - name: Setup
      run: |
        mkdir bin
        cd bin
        cmake ../ -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0 -DUSE_COREPCH=$PCH -DUSE_SCRIPTPCH=$PCH -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DBUILD_TESTING=1
        cd ..
    - name: Build
      run: |
        cd bin
        make -j 4 -k && make install
    - name: Unit tests
      run: |
        cd bin
        make test
    - name: Check executables
      run: |
        cd bin/check_install/bin
        ./authserver --version
        ./worldserver --version
    
    - name: Push changes
      if: pch == ON
      uses: ad-m/github-push-action@b007e7b818e33b04afd056e4c4b57ba917145d7a
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ matrix.branch }}
        repository: Rochet2/TrinityCore
